### ISSUE TITLE
Platform error sensor.jumbo - No module named 'jumbo_api'

### ISSUE THREAD

**Issue by Voxxie** [peternijssen/home-assistant-jumbo#1]
I installed the custom component manually because its not yet listed at HACS. 

But i am getting this error in the logging: 
Platform error sensor.jumbo - No module named 'jumbo_api'

I am using an Intel NUC with HassOS

**Comment by peternijssen** [comment]
Did the work around made a difference btw? https://community.home-assistant.io/t/jumbo-com-integration-dutch-supermarket/190438/9?u=ptnijssen

Then at least it's not caused by a potential copy/paste error :)

**Comment by Voxxie** [comment]
Found it, it was really stupid from my side...

What Ii did: 
1) Install via HACS
2) Changed my configuartion.yaml
3) Tried to reboot, that gave me the error message.

What is working
1) Install via HACS
2) Reboot Home Assistant
3) Change configuration.yaml
4) Reboot Home Assistant
