### ISSUE TITLE
feature request: Please add total amount (price) for basket in attributes field

### ISSUE THREAD

**Issue by rolfberkenbosch** [peternijssen/home-assistant-jumbo#3]
Thanks for your great addon!

Please add total amount (price) for the current basket in attributes field. This can help to make an automation script for example if a price is above a threshold to notify that the order can be place at Jumbo.

**Comment by peternijssen** [comment]
https://github.com/peternijssen/home-assistant-jumbo/releases/tag/v0.4.0
